# wsi/config.py

INDICATORS = {
    "Education": {"dimension": "Equity", "invert": False, "fill": "income_avg"},
    "Employment": {"dimension": "Equity", "invert": False, "fill": "income_avg"},
    "Parliamentary Representation": {
        "dimension": "Equity",
        "invert": False,
        "fill": "region_avg",
    },
    "Poverty": {"dimension": "Equity", "invert": True, "fill": "income_avg"},
    "Legal Protection Index": {
        "dimension": "Equity",
        "invert": False,
        "fill": "region_avg",
    },
    "Son Bias": {"dimension": "Protection", "invert": True, "fill": "region_avg"},
    "Maternal Mortality": {
        "dimension": "Protection",
        "invert": True,
        "fill": "region_avg",
    },
    "Attitudes Towards Violence": {
        "dimension": "Protection",
        "invert": True,
        "fill": "region_avg",
    },
    "Child Marriage": {"dimension": "Protection", "invert": True, "fill": "region_avg"},
    "Access Water Sanitation": {
        "dimension": "Resources",
        "invert": False,
        "fill": "region_avg",
    },
    "Access Electricity": {
        "dimension": "Resources",
        "invert": False,
        "fill": "region_avg",
    },
    "Cell Phone Use": {
        "dimension": "Resources",
        "invert": False,
        "fill": "region_avg",
    },
    "Financial Inclusion": {
        "dimension": "Resources",
        "invert": False,
        "fill": "income_avg",
    },
}

EXCLUDE_ISO = {
    "ABW",
    "AND",
    "ASM",
    "BMU",
    "CHI",
    "COK",
    "CUW",
    "CYM",
    "DMA",
    "FRO",
    "GIB",
    "GRL",
    "GUM",
    "IMN",
    "KNA",
    "LIE",
    "MAC",
    "MAF",
    "MCO",
    "MNP",
    "NCL",
    "NIU",
    "PRK",
    "PYF",
    "SXM",
    "TCA",
    "TKL",
    "TWN",
    "VGB",
    "VIR",
    "WLF",
    "XKX",
}

RENAME_INDICATOR_SCORE = {
    "Education": "Education",
    "Employment": "Employment",
    "Parliamentary Representation": "Parliamentary Representation",
    "Poverty": "Poverty Alleviation",
    "Legal Protection Index": "Legal Protection",
    "Son Bias": "Gender-Equitable Births",
    "Maternal Mortality": "Maternal Survival",
    "Attitudes Towards Violence": "Attitudes Against Violence",
    "Child Marriage": "Absence of Child Marriage",
    "Access Water Sanitation": "Water Sanitation Access",
    "Access Electricity": "Electricity Access",
    "Cell Phone Use": "Cell Phone Use",
    "Financial Inclusion": "Financial Inclusion",
}
