# -*- coding: utf-8 -*-
"""standard ISO to subregion mappings"""

# source: chatgpt
CODE_SUBREGION = {
    "AFG": "Southern Asia",
    "AUS": "Australia and New Zealand",
    "BGD": "Southern Asia",
    "BTN": "Southern Asia",
    "BRN": "Southeast Asia",
    "KHM": "Southeast Asia",
    "KOR": "East Asia",
    "PRK": "East Asia",
    "IND": "Southern Asia",
    "IDN": "Southeast Asia",
    "JPN": "East Asia",
    "LAO": "Southeast Asia",
    "MYS": "Southeast Asia",
    "MDV": "Southern Asia",
    "MNG": "East Asia",
    "MMR": "Southeast Asia",
    "NPL": "Southern Asia",
    "NZL": "Australia and New Zealand",
    "PAK": "Southern Asia",
    "CHN": "East Asia",
    "PHL": "Southeast Asia",
    "SGP": "Southeast Asia",
    "LKA": "Southern Asia",
    "TWN": "East Asia",
    "THA": "Southeast Asia",
    "TLS": "Southeast Asia",
    "VNM": "Southeast Asia",
    "NCL": "Melanesia",
    "COK": "Polynesia",
    "FSM": "Micronesia",
    "PNG": "Melanesia",
    "WSM": "Polynesia",
    "TON": "Polynesia",
    "NIU": "Polynesia",
    "FJI": "Melanesia",
    "KIR": "Micronesia",
    "MHL": "Micronesia",
    "NRU": "Micronesia",
    "PLW": "Micronesia",
    "VUT": "Melanesia",
    "SLB": "Melanesia",
    "TUV": "Polynesia",
    "HKG": "East Asia",
    "TKL": "Polynesia",
    "WLF": "Polynesia",
    "MNP": "Micronesia",
    "ASM": "Polynesia",
    "PYF": "Polynesia",
}
