# -*- coding: utf-8 -*-
"""Any country text to standard ISO mappings"""

# Country name (any variant found in data sources) to ISO code map
COUNTRY_ISO = {
    "Aruba": "ABW",
    "Afghanistan": "AFG",
    "Angola": "AGO",
    "Albania": "ALB",
    "Netherlands Antilles": "ANT",
    "United Arab Emirates": "ARE",
    "Argentina": "ARG",
    "Armenia": "ARM",
    "Australia": "AUS",
    "Austria": "AUT",
    "Azerbaijan": "AZE",
    "Burundi": "BDI",
    "Belgium": "BEL",
    "Benin": "BEN",
    "Burkina Faso": "BFA",
    "Bangladesh": "BGD",
    "Bulgaria": "BGR",
    "Bahrain": "BHR",
    "Bahamas": "BHS",
    "Bosnia and Herzegovina": "BIH",
    "Belarus": "BLR",
    "Belize": "BLZ",
    "Bolivia (Plurinational State of)": "BOL",
    "Brazil": "BRA",
    "Barbados": "BRB",
    "Brunei Darussalam": "BRN",
    "Bhutan": "BTN",
    "Botswana": "BWA",
    "Canada": "CAN",
    "Switzerland": "CHE",
    "Chile": "CHL",
    "China": "CHN",
    "Côte d'Ivoire": "CIV",
    "Cameroon": "CMR",
    "Congo, Democratic Republic of the": "COD",
    "Congo": "COG",
    "Cook Islands": "COK",
    "Colombia": "COL",
    "Comoros": "COM",
    "Cabo Verde": "CPV",
    "Costa Rica": "CRI",
    "Cuba": "CUB",
    "Curaçao": "CUW",
    "Cayman Islands": "CYM",
    "Cyprus": "CYP",
    "Czechia": "CZE",
    "Germany": "DEU",
    "Djibouti": "DJI",
    "Denmark": "DNK",
    "Dominican Republic": "DOM",
    "Algeria": "DZA",
    "Ecuador": "ECU",
    "Egypt": "EGY",
    "Spain": "ESP",
    "Estonia": "EST",
    "Ethiopia": "ETH",
    "Finland": "FIN",
    "Fiji": "FJI",
    "Falkland Islands, Malvinas": "FLK",
    "France": "FRA",
    "Micronesia (Federated States of)": "FSM",
    "Gabon": "GAB",
    "United Kingdom of Great Britain and Northern Ireland": "GBR",
    "Georgia": "GEO",
    "Guernsey": "GGY",
    "Ghana": "GHA",
    "Guinea": "GIN",
    "Gambia": "GMB",
    "Guinea-Bissau": "GNB",
    "Greece": "GRC",
    "Grenada": "GRD",
    "Guatemala": "GTM",
    "Guyana": "GUY",
    "Hong Kong, China": "HKG",
    "Honduras": "HND",
    "Croatia": "HRV",
    "Haiti": "HTI",
    "Hungary": "HUN",
    "Indonesia": "IDN",
    "Isle of Man": "IMN",
    "India": "IND",
    "Ireland": "IRL",
    "Iran (Islamic Republic of)": "IRN",
    "Iraq": "IRQ",
    "Iceland": "ISL",
    "Israel": "ISR",
    "Italy": "ITA",
    "Jamaica": "JAM",
    "Jordan": "JOR",
    "Japan": "JPN",
    "Kenya": "KEN",
    "Kyrgyzstan": "KGZ",
    "Cambodia": "KHM",
    "Kiribati": "KIR",
    "Saint Kitts and Nevis": "KNA",
    "Republic of Korea": "KOR",
    "Kosovo": "KOS",
    "Lao People's Democratic Republic": "LAO",
    "Lebanon": "LBN",
    "Liberia": "LBR",
    "Libya": "LBY",
    "Saint Lucia": "LCA",
    "Liechtenstein": "LIE",
    "Sri Lanka": "LKA",
    "Lesotho": "LSO",
    "Lithuania": "LTU",
    "Luxembourg": "LUX",
    "Latvia": "LVA",
    "Macao, China": "MAC",
    "Morocco": "MAR",
    "Monaco": "MCO",
    "Republic of Moldova": "MDA",
    "Madagascar": "MDG",
    "Maldives": "MDV",
    "Mexico": "MEX",
    "Marshall Islands": "MHL",
    "North Macedonia": "MKD",
    "Mali": "MLI",
    "Malta": "MLT",
    "Myanmar": "MMR",
    "Montenegro": "MNE",
    "Mongolia": "MNG",
    "Mozambique": "MOZ",
    "Mauritania": "MRT",
    "Montserrat": "MSR",
    "Mauritius": "MUS",
    "Malawi": "MWI",
    "Malaysia": "MYS",
    "Namibia": "NAM",
    "New Caledonia": "NCL",
    "Niger": "NER",
    "Nigeria": "NGA",
    "Nicaragua": "NIC",
    "Niue": "NIU",
    "Netherlands": "NLD",
    "Norway": "NOR",
    "Nepal": "NPL",
    "Nauru": "NRU",
    "New Zealand": "NZL",
    "Oman": "OMN",
    "Pakistan": "PAK",
    "Panama": "PAN",
    "Peru": "PER",
    "Philippines": "PHL",
    "Palau": "PLW",
    "Papua New Guinea": "PNG",
    "Poland": "POL",
    "Puerto Rico": "PRI",
    "Portugal": "PRT",
    "Paraguay": "PRY",
    "Occupied Palestinian Territory": "PSE",
    "French Polynesia": "PYF",
    "Qatar": "QAT",
    "Réunion": "REU",
    "Romania": "ROU",
    "Russian Federation": "RUS",
    "Rwanda": "RWA",
    "Sudan": "SDN",
    "Senegal": "SEN",
    "Singapore": "SGP",
    "Solomon Islands": "SLB",
    "Sierra Leone": "SLE",
    "El Salvador": "SLV",
    "San Marino": "SMR",
    "Somalia": "SOM",
    "Serbia": "SRB",
    "South Sudan": "SSD",
    "Sao Tome and Principe": "STP",
    "Suriname": "SUR",
    "Slovakia": "SVK",
    "Slovenia": "SVN",
    "Sweden": "SWE",
    "Eswatini": "SWZ",
    "Seychelles": "SYC",
    "Syrian Arab Republic": "SYR",
    "Chad": "TCD",
    "Togo": "TGO",
    "Thailand": "THA",
    "Tajikistan": "TJK",
    "Tokelau": "TKL",
    "Timor-Leste": "TLS",
    "Tonga": "TON",
    "Trinidad and Tobago": "TTO",
    "Tunisia": "TUN",
    "Türkiye": "TUR",
    "Tuvalu": "TUV",
    "Taiwan, China": "TWN",
    "Tanzania, United Republic of": "TZA",
    "Uganda": "UGA",
    "Ukraine": "UKR",
    "Uruguay": "URY",
    "United States of America": "USA",
    "Uzbekistan": "UZB",
    "Venezuela (Bolivarian Republic of)": "VEN",
    "Viet Nam": "VNM",
    "Vanuatu": "VUT",
    "Wallis and Futuna": "WLF",
    "Samoa": "WSM",
    "Yemen": "YEM",
    "South Africa": "ZAF",
    "Zambia": "ZMB",
    "Zimbabwe": "ZWE",
    "Eritrea": "ERI",
    "Dem. People's Rep. of Korea": "PRK",
    "Turkmenistan": "TKM",
    "United Rep. of Tanzania": "TZA",
    "Czech Republic": "CZE",
    "Kazakstan": "KAZ",
    "Cape Verde": "CPV",
    "United Kingdom": "GBR",
    "Saint Vincent & the Grenadines": "VCT",
    "Dominica": "DMA",
    "Lao People's Democratic Rep.": "LAO",
    "Equatorial Guinea": "GNQ",
    "Cte d'Ivoire": "CIV",
    "Bolivia": "BOL",
    "Venezuela": "VEN",
    "Antigua and Barbuda": "ATG",
    "Zaire": "COD",  # Zaire is the old name for the Democratic Republic of the Congo
    "Iran (Islamic Rep. of)": "IRN",
    "Andorra": "AND",
    "Central African Republic": "CAF",
    "The F.Y.R. of Macedonia": "MKD",
    "Swaziland": "SWZ",  # Swaziland is now Eswatini
    "Turkey": "TUR",
    "Kuwait": "KWT",
    "Micronesia (Fed. States of)": "FSM",
    "Libyan Arab Jamahiriya": "LBY",  # Old name for Libya
    "Yugoslavia": "YUG",  # Old name for the former country
    "Kazakhstan": "KAZ",
    "Cote d'Ivoire": "CIV",  # Duplicate entry with "Cte d'Ivoire"
    "The f.Y.R. of Macedonia": "MKD",  # Same as "The F.Y.R. of Macedonia"
    "Fiji Islands": "FJI",
    "Dem. Rep. of East Timor": "TLS",  # East Timor is now Timor-Leste
    "Serbia and Montenegro": "SMR",  # Was a country that split into Serbia and Montenegro
    "Saudi Arabia": "SAU",
    "Dem. Republic of the Congo": "COD",  # Modern name for Zaire
    "United Republic of Tanzania": "TZA",  # Same as 'United Rep. of Tanzania'
    "Democratic People's Republic of Korea": "PRK",  # Same as "Dem. People's Rep. of Korea"
    "Saint Vincent and the Grenadines": "VCT",
    "Democratic Republic of the Congo": "COD",
    "Trkiye": "TUR",  # Corrected spelling of Turkey
    "Gambia (The)": "GMB",  # 'The Gambia'
    "State of Palestine": "PSE",
    "China, Hong Kong Special Administrative Region": "HKG",
    "Netherlands (Kingdom of the)": "NLD",
}


def get_iso(country_name: str) -> str:
    """
    Return the ISO3 code for a country name, or raises KeyError if not found.
    """
    try:
        return COUNTRY_ISO[country_name]
    except KeyError:
        raise KeyError(f"Unknown country name: {country_name}")
