# -*- coding: utf-8 -*-
"""standard ISO to subregion mappings"""

# source: chatgpt
CODE_SUBREGION = {
    # Asia-Pacific
    "AFG": "Southern Asia",
    "AUS": "Australia and New Zealand",
    "BGD": "Southern Asia",
    "BTN": "Southern Asia",
    "BRN": "Southeast Asia",
    "KHM": "Southeast Asia",
    "KOR": "East Asia",
    "PRK": "East Asia",
    "IND": "Southern Asia",
    "IDN": "Southeast Asia",
    "JPN": "East Asia",
    "LAO": "Southeast Asia",
    "MYS": "Southeast Asia",
    "MDV": "Southern Asia",
    "MNG": "East Asia",
    "MMR": "Southeast Asia",
    "NPL": "Southern Asia",
    "NZL": "Australia and New Zealand",
    "PAK": "Southern Asia",
    "CHN": "East Asia",
    "PHL": "Southeast Asia",
    "SGP": "Southeast Asia",
    "LKA": "Southern Asia",
    "TWN": "East Asia",
    "THA": "Southeast Asia",
    "TLS": "Southeast Asia",
    "VNM": "Southeast Asia",
    "NCL": "Melanesia",
    "COK": "Polynesia",
    "FSM": "Micronesia",
    "PNG": "Melanesia",
    "WSM": "Polynesia",
    "TON": "Polynesia",
    "NIU": "Polynesia",
    "FJI": "Melanesia",
    "KIR": "Micronesia",
    "MHL": "Micronesia",
    "NRU": "Micronesia",
    "PLW": "Micronesia",
    "VUT": "Melanesia",
    "SLB": "Melanesia",
    "TUV": "Polynesia",
    "HKG": "East Asia",
    "TKL": "Polynesia",
    "WLF": "Polynesia",
    "MNP": "Micronesia",
    "ASM": "Polynesia",
    "PYF": "Polynesia",
    # Africa (more granular)
    "DZA": "Northern Africa",
    "AGO": "Central Africa",
    "BEN": "Western Africa",
    "BFA": "Western Africa",
    "BDI": "Eastern Africa",
    "CMR": "Central Africa",
    "CPV": "Western Africa",
    "CAF": "Central Africa",
    "TCD": "Central Africa",
    "COM": "Eastern Africa",
    "COD": "Central Africa",
    "COG": "Central Africa",
    "DJI": "Eastern Africa",
    "EGY": "Northern Africa",
    "ERI": "Eastern Africa",
    "ETH": "Eastern Africa",
    "GAB": "Central Africa",
    "GMB": "Western Africa",
    "GHA": "Western Africa",
    "GIN": "Western Africa",
    "GNB": "Western Africa",
    "KEN": "Eastern Africa",
    "LBR": "Western Africa",
    "LBY": "Northern Africa",
    "MDG": "Eastern Africa",
    "MWI": "Eastern Africa",
    "MLI": "Western Africa",
    "MRT": "Western Africa",
    "MOZ": "Eastern Africa",
    "NAM": "Southern Africa",
    "NER": "Western Africa",
    "NGA": "Western Africa",
    "RWA": "Eastern Africa",
    "SDN": "Northern Africa",
    "SEN": "Western Africa",
    "SLE": "Western Africa",
    "SOM": "Eastern Africa",
    "SSD": "Eastern Africa",
    "SWZ": "Southern Africa",
    "TZA": "Eastern Africa",
    "TGO": "Western Africa",
    "UGA": "Eastern Africa",
    "ZAF": "Southern Africa",
    "ZMB": "Eastern Africa",
    "ZWE": "Eastern Africa",
    # Americas (more granular)
    "ATG": "Caribbean",
    "ARG": "South America",
    "BHS": "Caribbean",
    "BRB": "Caribbean",
    "BLZ": "Central America",
    "BMU": "Caribbean",
    "BOL": "South America",
    "BRA": "South America",
    "VGB": "Caribbean",
    "CAN": "North America",
    "CYM": "Caribbean",
    "CRI": "Central America",
    "CUB": "Caribbean",
    "DMA": "Caribbean",
    "DOM": "Caribbean",
    "ECU": "South America",
    "SLV": "Central America",
    "GRD": "Caribbean",
    "GTM": "Central America",
    "GUY": "South America",
    "HTI": "Caribbean",
    "HND": "Central America",
    "JAM": "Caribbean",
    "MEX": "Central America",
    "NIC": "Central America",
    "PAN": "Central America",
    "PRY": "South America",
    "PER": "South America",
    "PRI": "Caribbean",
    "SUR": "South America",
    "TTO": "Caribbean",
    "USA": "North America",
    "URY": "South America",
    "VEN": "South America",
    # Europe (more granular)
    "ALB": "Southern Europe",
    "AND": "Southern Europe",
    "BLR": "Eastern Europe",
    "BEL": "Western Europe",
    "BIH": "Southern Europe",
    "BGR": "Eastern Europe",
    "HRV": "Southern Europe",
    "CYP": "Southern Europe",
    "CZE": "Eastern Europe",
    "DNK": "Northern Europe",
    "EST": "Northern Europe",
    "FIN": "Northern Europe",
    "FRO": "Northern Europe",
    "FRA": "Western Europe",
    "DEU": "Western Europe",
    "GIB": "Southern Europe",
    "GRC": "Southern Europe",
    "GRL": "Northern Europe",
    "HUN": "Eastern Europe",
    "ISL": "Northern Europe",
    "IRL": "Northern Europe",
    "IMN": "Northern Europe",
    "ITA": "Southern Europe",
    "LVA": "Northern Europe",
    "LTU": "Northern Europe",
    "LUX": "Western Europe",
    "MLT": "Southern Europe",
    "MDA": "Eastern Europe",
    "MCO": "Western Europe",
    "MNE": "Southern Europe",
    "NLD": "Western Europe",
    "MKD": "Southern Europe",
    "NOR": "Northern Europe",
    "POL": "Eastern Europe",
    "PRT": "Southern Europe",
    "ROU": "Eastern Europe",
    "RUS": "Eastern Europe",
    "SMR": "Southern Europe",
    "SRB": "Southern Europe",
    "SVK": "Eastern Europe",
    "SVN": "Southern Europe",
    "ESP": "Southern Europe",
    "SWE": "Northern Europe",
    "CHE": "Western Europe",
    "GBR": "Northern Europe",
    # MENA (more granular)
    "ARE": "Middle East",
    "BHR": "Middle East",
    "DJI": "Eastern Africa",  # usually East Africa but often grouped in MENA context
    "EGY": "Northern Africa",
    "IRN": "Middle East",
    "IRQ": "Middle East",
    "ISR": "Middle East",
    "JOR": "Middle East",
    "KWT": "Middle East",
    "LBN": "Middle East",
    "LBY": "Northern Africa",
    "OMN": "Middle East",
    "QAT": "Middle East",
    "SAU": "Middle East",
    "SDN": "Northern Africa",
    "SYR": "Middle East",
    "TUN": "Northern Africa",
    "YEM": "Middle East",
    # other
    "ABW": "Caribbean",
    "ARM": "Western Asia",
    "AUT": "Western Europe",
    "AZE": "Western Asia",
    "BWA": "Southern Africa",
    "CHI": "Western Europe",
    "CHL": "South America",
    "CIV": "Western Africa",
    "COL": "South America",
    "CUW": "Caribbean",
    "GEO": "Western Asia",
    "GNQ": "Middle Africa",
    "GUM": "Micronesia",
    "KAZ": "Central Asia",
    "KGZ": "Central Asia",
    "KNA": "Caribbean",
    "LCA": "Caribbean",
    "LIE": "Western Europe",
    "LSO": "Southern Africa",
    "MAC": "East Asia",
    "MAF": "Caribbean",
    "MAR": "Northern Africa",
    "MUS": "Eastern Africa",  # Often grouped under Africa, island state
    "PSE": "Western Asia",
    "STP": "Middle Africa",
    "SXM": "Caribbean",
    "SYC": "Eastern Africa",
    "TCA": "Caribbean",
    "TJK": "Central Asia",
    "TKM": "Central Asia",
    "TUR": "Western Asia",
    "UKR": "Eastern Europe",
    "UZB": "Central Asia",
    "VCT": "Caribbean",
    "VIR": "Caribbean",
    "XKX": "Southern Europe",  # Kosovo, often included here
}
