# -*- coding: utf-8 -*-
"""standard ISO to CEVAW standard name mapping"""

# establishes which countries are in Asia Pacific and their standardised name
ALL_ISO_NAME = {
    "AFG": "Afghanistan",
    "AUS": "Australia",
    "BGD": "Bangladesh",
    "BTN": "Bhutan",
    "BRN": "Brunei",
    "KHM": "Cambodia",
    "KOR": "Republic of Korea (South Korea)",
    "PRK": "Democratic People's Republic of Korea (North Korea)",
    "IND": "India",
    "IDN": "Indonesia",
    "JPN": "Japan",
    "LAO": "Laos",
    "MYS": "Malaysia",
    "MDV": "Maldives",
    "MNG": "Mongolia",
    "MMR": "Myanmar",
    "NPL": "Nepal",
    "NZL": "New Zealand",
    "PAK": "Pakistan",
    "CHN": "China",
    "PHL": "Philippines",
    "SGP": "Singapore",
    "LKA": "Sri Lanka",
    "TWN": "Taiwan",
    "THA": "Thailand",
    "TLS": "Timor-Leste",  # economy code is 'TMP'
    "VNM": "Vietnam",
    "NCL": "New Caledonia",
    "COK": "Cook Islands",
    "FSM": "Micronesia",
    "PNG": "Papua New Guinea",
    "WSM": "Samoa",
    "TON": "Tonga",
    "NIU": "Niue",
    "FJI": "Fiji",
    "KIR": "Kiribati",
    "MHL": "Marshall Islands",
    "NRU": "Nauru",
    "PLW": "Palau",
    "VUT": "Vanuatu",
    "SLB": "Solomon Islands",
    "TUV": "Tuvalu",
    "HKG": "Hong Kong",
    "TKL": "Tokelau",
    "WLF": "Wallis and Futuna Islands",
    "MNP": "Northern Mariana Islands",
    "ASM": "American Samoa",
    "PYF": "French Polynesia",
    "ALB": "Albania",
    "DZA": "Algeria",
    "AND": "Andorra",
    "AGO": "Angola",
    "ATG": "Antigua and Barbuda",
    "ARG": "Argentina",
    "ARM": "Armenia",
    "ABW": "Aruba",
    "AUT": "Austria",
    "AZE": "Azerbaijan",
    "BHS": "Bahamas, The",
    "BHR": "Bahrain",
    "BRB": "Barbados",
    "BLR": "Belarus",
    "BEL": "Belgium",
    "BLZ": "Belize",
    "BEN": "Benin",
    "BMU": "Bermuda",
    "BOL": "Bolivia",
    "BIH": "Bosnia and Herzegovina",
    "BWA": "Botswana",
    "BRA": "Brazil",
    "VGB": "British Virgin Islands",
    "BGR": "Bulgaria",
    "BFA": "Burkina Faso",
    "BDI": "Burundi",
    "CPV": "Cabo Verde",
    "CMR": "Cameroon",
    "CAN": "Canada",
    "CYM": "Cayman Islands",
    "CAF": "Central African Republic",
    "TCD": "Chad",
    "CHI": "Channel Islands",
    "CHL": "Chile",
    "COL": "Colombia",
    "COM": "Comoros",
    "COD": "Congo, Dem. Rep.",
    "COG": "Congo, Rep.",
    "CRI": "Costa Rica",
    "CIV": "Côte d’Ivoire",
    "HRV": "Croatia",
    "CUB": "Cuba",
    "CUW": "Curaçao",
    "CYP": "Cyprus",
    "CZE": "Czechia",
    "DNK": "Denmark",
    "DJI": "Djibouti",
    "DMA": "Dominica",
    "DOM": "Dominican Republic",
    "ECU": "Ecuador",
    "EGY": "Egypt, Arab Rep.",
    "SLV": "El Salvador",
    "GNQ": "Equatorial Guinea",
    "ERI": "Eritrea",
    "EST": "Estonia",
    "SWZ": "Eswatini",
    "ETH": "Ethiopia",
    "FRO": "Faroe Islands",
    "FIN": "Finland",
    "FRA": "France",
    "GAB": "Gabon",
    "GMB": "Gambia, The",
    "GEO": "Georgia",
    "DEU": "Germany",
    "GHA": "Ghana",
    "GIB": "Gibraltar",
    "GRC": "Greece",
    "GRL": "Greenland",
    "GRD": "Grenada",
    "GUM": "Guam",
    "GTM": "Guatemala",
    "GIN": "Guinea",
    "GNB": "Guinea-Bissau",
    "GUY": "Guyana",
    "HTI": "Haiti",
    "HND": "Honduras",
    "HUN": "Hungary",
    "ISL": "Iceland",
    "IRN": "Iran, Islamic Rep.",
    "IRQ": "Iraq",
    "IRL": "Ireland",
    "IMN": "Isle of Man",
    "ISR": "Israel",
    "ITA": "Italy",
    "JAM": "Jamaica",
    "JOR": "Jordan",
    "KAZ": "Kazakhstan",
    "KEN": "Kenya",
    "XKX": "Kosovo",
    "KWT": "Kuwait",
    "KGZ": "Kyrgyz Republic",
    "LVA": "Latvia",
    "LBN": "Lebanon",
    "LSO": "Lesotho",
    "LBR": "Liberia",
    "LBY": "Libya",
    "LIE": "Liechtenstein",
    "LTU": "Lithuania",
    "LUX": "Luxembourg",
    "MAC": "Macao SAR, China",
    "MDG": "Madagascar",
    "MWI": "Malawi",
    "MLI": "Mali",
    "MLT": "Malta",
    "MRT": "Mauritania",
    "MUS": "Mauritius",
    "MEX": "Mexico",
    "MDA": "Moldova",
    "MCO": "Monaco",
    "MNE": "Montenegro",
    "MAR": "Morocco",
    "MOZ": "Mozambique",
    "NAM": "Namibia",
    "NLD": "Netherlands",
    "NIC": "Nicaragua",
    "NER": "Niger",
    "NGA": "Nigeria",
    "MKD": "North Macedonia",
    "NOR": "Norway",
    "OMN": "Oman",
    "PAN": "Panama",
    "PRY": "Paraguay",
    "PER": "Peru",
    "POL": "Poland",
    "PRT": "Portugal",
    "PRI": "Puerto Rico",
    "QAT": "Qatar",
    "ROU": "Romania",
    "RUS": "Russian Federation",
    "RWA": "Rwanda",
    "SMR": "San Marino",
    "STP": "São Tomé and Príncipe",
    "SAU": "Saudi Arabia",
    "SEN": "Senegal",
    "SRB": "Serbia",
    "SYC": "Seychelles",
    "SLE": "Sierra Leone",
    "SXM": "Sint Maarten (Dutch part)",
    "SVK": "Slovak Republic",
    "SVN": "Slovenia",
    "SOM": "Somalia",
    "ZAF": "South Africa",
    "SSD": "South Sudan",
    "ESP": "Spain",
    "KNA": "St. Kitts and Nevis",
    "LCA": "St. Lucia",
    "MAF": "St. Martin (French part)",
    "VCT": "St. Vincent and the Grenadines",
    "SDN": "Sudan",
    "SUR": "Suriname",
    "SWE": "Sweden",
    "CHE": "Switzerland",
    "SYR": "Syrian Arab Republic",
    "TJK": "Tajikistan",
    "TZA": "Tanzania",
    "TGO": "Togo",
    "TTO": "Trinidad and Tobago",
    "TUN": "Tunisia",
    "TUR": "Türkiye",
    "TKM": "Turkmenistan",
    "TCA": "Turks and Caicos Islands",
    "UGA": "Uganda",
    "UKR": "Ukraine",
    "ARE": "United Arab Emirates",
    "GBR": "United Kingdom",
    "USA": "United States",
    "URY": "Uruguay",
    "UZB": "Uzbekistan",
    "VEN": "Venezuela, RB",
    "VIR": "Virgin Islands (U.S.)",
    "PSE": "West Bank and Gaza",
    "YEM": "Yemen, Rep.",
    "ZMB": "Zambia",
    "ZWE": "Zimbabwe",
}
